### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by leoarry** [shinyorg/shiny#1030]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [X] Android 8
- [X] Android 9
- [X] Android 10
- [X] Android 11
- [X] Android 12

### What platform(s) are effected?

- [X] MAUI
- [ ] Xamarin Native
- [ ] Xamarin Forms

### Steps To Reproduce

The method GattCharacteristic.GetDescriptors() is not working, throwing a cast exception every time you try to implement it.
At row 185 of GattCharacteristic.cs (Android) there is a call to Cast<IList<IGattDescriptor>>() which cannot be performed. 
I tryed to modified as follow and is now working correctly (tested from phisical android device)
public override IObservable<IList<IGattDescriptor>> GetDescriptors() =>
Observable.Create<IList<IGattDescriptor>>(obs =>
                     {
                         var list = this.native
                                         .Descriptors
                                         .Select(x => new GattDescriptor(this, this.context, x))
                                         .Cast<IGattDescriptor>()
                                         .ToList();
                         obs.OnNext(list);
                         return Disposable.Empty;
                     });

### Expected Behavior

Get me the list of descriptors

### Actual Behavior

Generate exception

### Exception or Log output

   at System.Linq.Enumerable.<CastIterator>d__38`1[[System.Collections.Generic.IList`1[[Shiny.BluetoothLE.IGattDescriptor, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._[[System.Collections.Generic.IList`1[[Shiny.BluetoothLE.IGattDescriptor, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].LoopRec(IScheduler scheduler) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/ToObservable.cs:line 86
--- End of stack trace from previous location ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:line 19
   at System.Reactive.ExceptionHelpers.Throw(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:line 16
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in /_/Rx.NET/Source/src/System.Reactive/Internal/Stubs.cs:line 16
   at System.Reactive.AnonymousSafeObserver`1[[System.Collections.Generic.IList`1[[Shiny.BluetoothLE.IGattDescriptor, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 62
   at System.Reactive.Sink`1[[System.Collections.Generic.IList`1[[Shiny.BluetoothLE.IGattDescriptor, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._[[System.Collections.Generic.IList`1[[Shiny.BluetoothLE.IGattDescriptor, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].LoopRec(IScheduler scheduler) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/ToObservable.cs:line 102
   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._.<>c[[System.Collections.Generic.IList`1[[Shiny.BluetoothLE.IGattDescriptor, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<Run>b__3_0(IScheduler innerScheduler, _ this) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/ToObservable.cs:line 55
   at System.Reactive.Concurrency.ScheduledItem`2[[System.TimeSpan, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._[[System.Collections.Generic.IList`1[[Shiny.BluetoothLE.IGattDescriptor, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Reactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].InvokeCore() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/ScheduledItem.cs:line 205
   at System.Reactive.Concurrency.ScheduledItem`1[[System.TimeSpan, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/ScheduledItem.cs:line 44
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/CurrentThreadScheduler.cs:line 168
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[ValueTuple`2](ValueTuple`2 state, TimeSpan dueTime, Func`3 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/CurrentThreadScheduler.cs:line 118
   at System.Reactive.Concurrency.LocalScheduler.Schedule[ValueTuple`2](ValueTuple`2 state, Func`3 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/LocalScheduler.cs:line 32
   at System.Reactive.Concurrency.Scheduler.ScheduleAction[ValueTuple`2](IScheduler scheduler, ValueTuple`2 state, Action`1 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 61
   at System.Reactive.Producer`2[[System.Collections.Generic.IList`1[[Shiny.BluetoothLE.IGattDescriptor, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._[[System.Collections.Generic.IList`1[[Shiny.BluetoothLE.IGattDescriptor, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Reactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 119
   at System.Reactive.Producer`2[[System.Collections.Generic.IList`1[[Shiny.BluetoothLE.IGattDescriptor, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._[[System.Collections.Generic.IList`1[[Shiny.BluetoothLE.IGattDescriptor, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Reactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].Subscribe(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 97
   at System.ObservableExtensions.Subscribe[IList`1](IObservable`1 source, Action`1 onNext) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 63
   at SmartDsp.ViewModels.HardwareControlsViewModel.<>c.<Refresh>b__3_1(GattCharacteristicResult chrVal) in C:\Users\larri\source\repos\SmartDsp\SmartDsp\ViewModels\HardwareControls\HardwareControlsViewModel.cs:line 109

### Code Sample

original from GattCharacteristic.cs (Android)
public override IObservable<IList<IGattDescriptor>> GetDescriptors() =>
        this.native
            .Descriptors
            .Select(x => new GattDescriptor(this, this.context, x))
            .Cast<IGattDescriptor>()
            .ToList()
            .Cast<IList<IGattDescriptor>>()
            .ToObservable();

I modified as follow ad works.
public override IObservable<IList<IGattDescriptor>> GetDescriptors() =>
Observable.Create<IList<IGattDescriptor>>(obs =>
                     {
                         var list = this.native
                                         .Descriptors
                                         .Select(x => new GattDescriptor(this, this.context, x))
                                         .Cast<IGattDescriptor>()
                                         .ToList();
                         obs.OnNext(list);
                         return Disposable.Empty;
                     });

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Please note that I’m not taking issues for alphas at this time (I only take issues for stable hence the checkbox).  I’ll take a look at your fix for a future alpha

**Comment by leoarry** [comment]
Please note that the bug is also on the stable version.
