### ISSUE TITLE
Update configuration API to support delegate methods

### ISSUE THREAD

**Issue by dansiegel** [shinyorg/shiny#12]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [x] UWP
 - [x] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [x] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of OS(s) listed above with issue

n/a

## Version of Library

1.0.0.7-beta

## Expected Behavior

Since we're following an ASP.NET Core startup pattern with IServiceCollection we should also follow the standard API configuration patterns by allowing a delegate method to configure the request rather than passing in a complete request.

```cs
public void ConfigureServices(IServiceCollection services)
{
    services.UseGps<BackgroudnGpsRunnerDelegate>(r => {
        r.UseBackground = true;
        r.DeferredTime = TimeSpan.FromSeconds(10);
    });
}
```

## Actual Behavior

```cs
public void ConfigureServices(IServiceCollection services)
{
    var request = new GpsRequest { UseBackground = true, DeferredTime = TimeSpan.FromSeconds(3) };
    services.UseGps<BackgroudnGpsRunnerDelegate>(request);
}
```

**Comment by aritchie** [comment]
Should already be in 1.0.0.9-beta on nuget

**Comment by dansiegel** [comment]
I don't see a 1.0.0.9-beta but I do see that this is in 1.0.0.8-beta... unfortunately something in the change to that new version now throws a Java.Lang.NullPointerException see the stack trace below. 

```
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticVoidMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <9ed4c1a7b8844cdcb5330cc881c1cd6a>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeVoidMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <9ed4c1a7b8844cdcb5330cc881c1cd6a>:0 
  at Android.Support.V4.App.ActivityCompat.RequestPermissions (Android.App.Activity activity, System.String[] permissions, System.Int32 requestCode) [0x00061] in <16cea522aac44605abdedfb79374e46c>:0 
  at Shiny.AndroidContext+<>c__DisplayClass20_0.<RequestAccess>b__0 (System.IObserver`1[T] ob) [0x0008d] in D:\a\1\s\src\Shiny.Core\Platforms\Android\AndroidContext.cs:123 
  at System.Reactive.Linq.QueryLanguage+CreateWithActionDisposable`1[TSource].SubscribeCore (System.IObserver`1[T] observer) [0x00000] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.ObservableBase`1[T].Subscribe (System.IObserver`1[T] observer) [0x00037] in <269857168607470d991a5a72ee3bb154>:0 
--- End of stack trace from previous location where exception was thrown ---

  at Shiny.Locations.GpsManagerImpl.StartListener (Shiny.Locations.GpsRequest request) [0x00051] in D:\a\1\s\src\Shiny.Locations\Platforms\Android\GpsManagerImpl.cs:54 
  at Shiny.Locations.ServiceCollectionExtensions+<>c__DisplayClass3_1`1[T].<UseGps>b__2 () [0x00041] in D:\a\1\s\src\Shiny.Locations\Platforms\Shared\ServiceCollectionExtensions.cs:81 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.ExceptionHelpers.Throw (System.Exception exception) [0x0000a] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Stubs+<>c.<.cctor>b__2_1 (System.Exception ex) [0x00000] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.AnonymousObserver`1[T].OnErrorCore (System.Exception error) [0x00000] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.ObserverBase`1[T].OnError (System.Exception error) [0x0001c] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Linq.ObservableImpl.ConcatMany`1+ConcatManyOuterObserver[T].Drain () [0x00059] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Linq.ObservableImpl.ConcatMany`1+ConcatManyOuterObserver[T].OnNext (System.IObservable`1[T] value) [0x0000c] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Sink`1[TTarget].ForwardOnNext (TTarget value) [0x00000] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Linq.ObservableImpl.Select`2+Selector+_[TSource,TResult].OnNext (TSource value) [0x00021] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Sink`1[TTarget].ForwardOnNext (TTarget value) [0x00000] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Linq.ObservableImpl.Take`1+Count+_[TSource].OnNext (TSource value) [0x00017] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Sink`1[TTarget].ForwardOnNext (TTarget value) [0x00000] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Linq.ObservableImpl.Where`1+Predicate+_[TSource].OnNext (TSource value) [0x0001e] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Linq.ObservableImpl.ReturnImmediate`1[TSource].Run (System.IObserver`1[T] observer) [0x00000] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.BasicProducer`1[TSource].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00052] in <269857168607470d991a5a72ee3bb154>:0 
  at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Sink`2[TSource,TTarget].Run (System.IObservable`1[T] source) [0x00000] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Linq.ObservableImpl.Where`1+Predicate[TSource].Run (System.Reactive.Linq.ObservableImpl.Where`1+Predicate+_[TSource] sink) [0x00000] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Producer`2[TTarget,TSink].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00060] in <269857168607470d991a5a72ee3bb154>:0 
  at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Sink`2[TSource,TTarget].Run (System.IObservable`1[T] source) [0x00000] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Linq.ObservableImpl.Take`1+Count[TSource].Run (System.Reactive.Linq.ObservableImpl.Take`1+Count+_[TSource] sink) [0x00000] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Producer`2[TTarget,TSink].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00060] in <269857168607470d991a5a72ee3bb154>:0 
  at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Sink`2[TSource,TTarget].Run (System.IObservable`1[T] source) [0x00000] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Linq.ObservableImpl.Select`2+Selector[TSource,TResult].Run (System.Reactive.Linq.ObservableImpl.Select`2+Selector+_[TSource,TResult] sink) [0x00000] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Producer`2+<>c[TTarget,TSink].<SubscribeRaw>b__1_0 (System.ValueTuple`2[T1,T2] tuple) [0x00000] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Concurrency.Scheduler+<>c__75`1[TState].<ScheduleAction>b__75_0 (System.Reactive.Concurrency.IScheduler _, System.ValueTuple`2[T1,T2] tuple) [0x00000] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState] (TState state, System.TimeSpan dueTime, System.Func`3[T1,T2,TResult] action) [0x0004e] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Concurrency.LocalScheduler.Schedule[TState] (TState state, System.Func`3[T1,T2,TResult] action) [0x0000e] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Concurrency.Scheduler.ScheduleAction[TState] (System.Reactive.Concurrency.IScheduler scheduler, TState state, System.Action`1[T] action) [0x00024] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Producer`2[TTarget,TSink].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00039] in <269857168607470d991a5a72ee3bb154>:0 
  at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <269857168607470d991a5a72ee3bb154>:0 
  at System.Reactive.Linq.ObservableImpl.ConcatMany`1[T].Subscribe (System.IObserver`1[T] observer) [0x00015] in <269857168607470d991a5a72ee3bb154>:0 
  at System.ObservableExtensions.Subscribe[T] (System.IObservable`1[T] source) [0x00023] in <269857168607470d991a5a72ee3bb154>:0 
  at Shiny.Extensions.SubscribeAsync[T] (System.IObservable`1[T] observable, System.Func`1[TResult] onNextAsync) [0x0000d] in D:\a\1\s\src\Shiny.Core\Extensions_Rx.cs:201 
  at Shiny.Locations.ServiceCollectionExtensions+<>c__DisplayClass3_0`1[T].<UseGps>b__0 (System.IServiceProvider sp) [0x00019] in D:\a\1\s\src\Shiny.Locations\Platforms\Shared\ServiceCollectionExtensions.cs:72 
  at Shiny.Extensions.RunPostBuildActions (System.IServiceProvider container) [0x00014] in D:\a\1\s\src\Shiny.Core\Extensions_Services.cs:83 
  at Shiny.ShinyHost.InitPlatform (Shiny.IStartup startup, System.Action`1[T] platformBuild) [0x00051] in D:\a\1\s\src\Shiny.Core\ShinyHost.cs:76 
  at Shiny.AndroidShinyHost.Init (Android.App.Application androidApp, Shiny.IStartup startup, System.Action`1[T] platformBuild) [0x00027] in D:\a\1\s\src\Shiny.Core\Platforms\Android\AndroidShinyHost.cs:24 
  at NCX.Mobile.Droid.Services.ServiceStackAndroid.Initialize (Android.App.Application androidApp) [0x0000f] in C:\Repos\NCX\ncx-mobile-v2\NCX.Mobile\NCX.Mobile.Droid\Services\ServiceStackAndroid.cs:25 
  --- End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.requestPermissions(java.lang.String[], int)' on a null object reference
	at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:502)
	at md5037c1b45a73a89d8c6b0ad16b71e1090.App.n_onCreate(Native Method)
	at md5037c1b45a73a89d8c6b0ad16b71e1090.App.onCreate(App.java:25)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1176)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6118)
	at android.app.ActivityThread.access$1200(ActivityThread.java:213)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1807)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6923)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

```

**Comment by aritchie** [comment]
by 1.0.0.9, I meant 1.0.0.8 ;)

I dropped out monoandroid81 in the latest beta.  Make sure your target is android9

**Comment by dansiegel** [comment]
doesn't everyone target latest? it is targeting Android 9

**Comment by aritchie** [comment]
They should - but not always.  
There is a bug (missing implementation) as part of the new "auto-start" mechanism.

**Comment by aritchie** [comment]
The auto-start bug is fixed in the next release.  The mechanism will request permission when/if an activity is detected.
