### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mabulla** [shinyorg/shiny#1218]
### Component/Nuget

Other

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)

### Version(s) of Operation Systems

tested and occured on Android 14 and Android 11

### What platform(s) are effected?

- [ ] MAUI
- [ ] Native
- [X] Classic Xamarin
- [ ] Other

### Steps To Reproduce

scan NFC-Tag or try to subscribe to WhenRecordsDetected or WhenTagsDetected.
reproducible-"just start to fail"-sample included.

### Expected Behavior

NFC-Tag is detected and subscribed Method is called

### Actual Behavior

throws exception and/or reloads the current page

### Exception or Log output

NFC Scanning failed: Java.Lang.IllegalStateException: Foreground dispatch can only be enabled when your activity is resumed
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00068] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/JniEnvironment.g.cs:11884 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001a] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:47 
  at Android.Nfc.NfcAdapter.EnableForegroundDispatch (Android.App.Activity activity, Android.App.PendingIntent intent, Android.Content.IntentFilter[] filters, System.String[][] techLists) [0x00084] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-33/mcw/Android.Nfc.NfcAdapter.cs:822 
  at Shiny.Nfc.NfcManager.<WhenTagsDetected>b__4_0 (System.IObserver`1[T] ob) [0x00095] in <27e1e9be762d4380b14a531852b4c7a2>:0 
  at System.Reactive.Linq.QueryLanguage+CreateWithActionDisposable`1[TSource].SubscribeCore (System.IObserver`1[T] observer) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Creation.cs:55 
  at System.Reactive.ObservableBase`1[T].ScheduledSubscribe (System.Reactive.AutoDetachObserver`1[T] autoDetachObserver) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/ObservableBase.cs:85 
  --- End of managed Java.Lang.IllegalStateException stack trace ---
java.lang.IllegalStateException: Foreground dispatch can only be enabled when your activity is resumed
	at android.nfc.NfcAdapter.enableForegroundDispatch(NfcAdapter.java:1764)
	at crc6466198e7311424276.MainActivity.n_onCreate(Native Method)
	at crc6466198e7311424276.MainActivity.onCreate(MainActivity.java:42)
	at android.app.Activity.performCreate(Activity.java:8198)
	at android.app.Activity.performCreate(Activity.java:8182)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)

### Code Sample

[ShinyNFCTest-Sample.zip](https://github.com/shinyorg/shiny/files/11344388/ShinyNFCTest-Sample.zip)

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
This could be something new in Android 13+.  Unfortunately, NFC is being removed in Shiny version 3.  I would suggest moving to another library as you can see it is no longer in the list of packages in the issue template any longer.

**Comment by mabulla** [comment]
Ok, i will use another library then. 
Thank you for the fast response and for shiny in general and keep up the good work!

**Comment by aritchie** [comment]
For what it's worth - I took a quick look.  You're actually calling for the NFC manager before the view is ready (and thus an activity for NFC to use).  This will likely be an issue in any NFC plugin you use.  I just ran my sample on my android phone and it appears to work fine.

**Comment by mabulla** [comment]
Thanks for the tip, but sadly that was not it. I now tried to delay the calling of the NFC manager but to no avail. 
The sample i quickly created may be not great, but its throws the same Exception as in our productive App. Whats different to the productive App is that the sample does not throw an Exeption on this.ShinyOnNewIntent(intent) in the MainActivity.cs... 
There the Debug output shows the following:

> Debug: Incoming NDEF Discovered 
**Java.Lang.IllegalStateException:** 'Call connect() first!'



i attached the crashlog if you got the time and want to look into it. I will now try to implement another library, maybe i´ve done something stupid..
[crashlog.txt](https://github.com/shinyorg/shiny/files/11345650/crashlog.txt)
