### ISSUE TITLE
[Bug]: Shiny Bluetooth Exception

### ISSUE THREAD

**Issue by TPitman-mindfiretechnology** [shinyorg/shiny#1227]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [X] Mac Catalyst
- [ ] Android (8+ supported)

### Version(s) of Operation Systems

MacOS 13

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Uno
- [ ] Manual

### Steps To Reproduce

1. Create new project.
2. Add Shiny Bluetooth Client and Hosting
3. Configure startup of UseShiny() to builder
4. Start app in Visual Studio on Mac

### Expected Behavior

Should run like it did in version beta-0040

### Actual Behavior

Crashes with an exception.

It runs fine on Android and iOS as far as I can tell. It only crashes on MacCatalyst

If this is just because MacCatalyst is not a priority I totally understand and will be patient.

FYI, being able to build and run on MacCatalyst is a huge time saver as I develop my application since I don't have to wait for deployment to a phone.

### Exception or Log output

`2023-05-19 09:28:30.570 ShinyBLETest[88674:6299324] Microsoft.MacCatalyst: An exception occurred while calling Runtime.Initialize`
`Value cannot be null. (Parameter 'key') (System.ArgumentNullException)
   at System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,` `PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,` `PublicKeyToken=7cec85d7bea7798e]].TryInsert(String key, Object value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,` `PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,` `PublicKeyToken=7cec85d7bea7798e]].Add(String key, Object value)
   at Registrar.DynamicRegistrar.SetAssemblyRegistered(String assembly)
   at ObjCRuntime.Class.Initialize(InitializationOptions* options)
   at ObjCRuntime.Runtime.Initialize(InitializationOptions* options)`
`2023-05-19 09:28:30.571 ShinyBLETest[88674:6299324] Microsoft.MacCatalyst: An exception occurred while calling Runtime.Initialize`
`Value cannot be null. (Parameter 'key') (System.ArgumentNullException)
   at System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,` `PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,` `PublicKeyToken=7cec85d7bea7798e]].TryInsert(String key, Object value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,` `PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,` `PublicKeyToken=7cec85d7bea7798e]].Add(String key, Object value)
   at Registrar.DynamicRegistrar.SetAssemblyRegistered(String assembly)
   at ObjCRuntime.Class.Initialize(InitializationOptions* options)
   at ObjCRuntime.Runtime.Initialize(InitializationOptions* options)`

### Code Sample

This is the same project I have been sending for testing.

https://github.com/TPitman-mindfiretechnology/ShinyBLETest.git

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
This one has nothing to do with Shiny.  I loaded up your sample just fine.  Check that your workloads are up-to-date

**Comment by TPitman-mindfiretechnology** [comment]
As far as I know I have the latest workloads:


   Installation Source: SDK 7.0.300
   Manifest Version:    7.0.86/7.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/7.0.100/microsoft.net.sdk.maui/WorkloadManifest.json
   Install Type:        FileBased

 [maui-ios]
   Installation Source: SDK 7.0.300
   Manifest Version:    7.0.86/7.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/7.0.100/microsoft.net.sdk.maui/WorkloadManifest.json
   Install Type:        FileBased

 [maui-android]
   Installation Source: SDK 7.0.300
   Manifest Version:    7.0.86/7.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/7.0.100/microsoft.net.sdk.maui/WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: SDK 7.0.300
   Manifest Version:    16.4.7060/7.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/7.0.100/microsoft.net.sdk.ios/WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: SDK 7.0.300
   Manifest Version:    16.4.7060/7.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/7.0.100/microsoft.net.sdk.maccatalyst/WorkloadManifest.json
   Install Type:        FileBased

Thoughts?

**Comment by aritchie** [comment]
So as new builds are released, shiny gets bumped forward on the SDK as well.  In this case, it is now on 7.0.200.  VS4mac is behind on the release path of vs4win.  There was a new release this week which is like the source of the issue.

Run `sudo dotnet workload update`

**Comment by aritchie** [comment]
Actually, yours match which is weird.  Delete bin/obj, restart vs.  

It's definitely something with the build product.  Shiny on iOS & mac share the exact same code

**Comment by TPitman-mindfiretechnology** [comment]
I had done a clean build including deleting the obj/bin folders and that had not worked. So I did that again and rebooted my computer and now it is all working with the latest beta-0092 from nuget.

Sorry to trouble you with this. Not sure what finally cleaned out what, but I am good now.

**Comment by aritchie** [comment]
If a repro is provided, I always look and no time is wasted.  In this case, it did end up hitting me with the latest vs4mac update which effected all of my previously built projects.  Deleting bin/obj or recloning a repo was the unfortunate fix
