### ISSUE TITLE
[Bug]: iOS System.IndexOutOfRangeException During BLE Scanning

### ISSUE THREAD

**Issue by jaredballen** [shinyorg/shiny#1274]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [X] iOS (13+ supported)
- [ ] Mac Catalyst
- [ ] Android (8+ supported)
- [ ] Windows (.NET 7 Target - only Core is currently supported, BLE is coming)

### Version(s) of Operation Systems

Testing using iOS 15.7.7

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Uno
- [ ] Manual

### Steps To Reproduce

This issue can only be reproduced using a device that is advertising manufacturing data in an incorrect format.

This issue was discovered because of a bug in the firmware on an embedded device. Instead, of sending manufacturing data with a 2-byte company ID followed by optional manufacturer-specific data, the device was not sending a company ID. It was only sending 1-byte of manufacture-specific data.

When the device was advertising, the App would crash in the Ctor of the `Shiny.BluetoothLE.AdvertisementData` class. It looks like it assumes at least 2-bytes of data are always sent.

I acknowledge that the root issue is incorrect data format from a client device; however, the library should be tolerant and should not crash. Android does not crash in this scenario, the manufacturing data is left out of the advertisement.

### Expected Behavior

If manufacturing data is formatted incorrectly, it should be ignored.

### Actual Behavior

IF manufacturing data is formatted incorrectly, the App crashes.

### Exception or Log output

Unhandled managed exception: Index was outside the bounds of the array. (System.IndexOutOfRangeException)
   at Shiny.BluetoothLE.AdvertisementData.<>c.<.ctor>b__7_3(NSObject x)
   at Shiny.BluetoothLE.AdvertisementData.<>c__DisplayClass20_0`1[[Shiny.BluetoothLE.ManufacturerData, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]].<GetLazy>b__0()
   at System.Lazy`1[[Shiny.BluetoothLE.ManufacturerData, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]].ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1[[Shiny.BluetoothLE.ManufacturerData, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1[[Shiny.BluetoothLE.ManufacturerData, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]].CreateValue()
   at System.Lazy`1[[Shiny.BluetoothLE.ManufacturerData, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Value()
   at Shiny.BluetoothLE.AdvertisementData.get_ManufacturerData()
   at fmr_configurator.Device.DeviceService.<StartScan>b__14_0(ScanResult result) in /Users/jallen/Workspace/fmr-configurator/fmr-configurator/Device/DeviceService.cs:line 106
   at Shiny.BluetoothLE.Managed.ManagedScan.<>c__DisplayClass30_0.<Start>b__1(IList`1 scanResults)
   at System.Reactive.AnonymousSafeObserver`1[[System.Collections.Generic.IList`1[[Shiny.BluetoothLE.ScanResult, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnNext(IList`1 value)
   at System.Reactive.Sink`1[[System.Collections.Generic.IList`1[[Shiny.BluetoothLE.ScanResult, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ForwardOnNext(IList`1 value)
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._[[System.Collections.Generic.IList`1[[Shiny.BluetoothLE.ScanResult, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnNext(IList`1 value)
   at System.Reactive.Sink`1[[System.Collections.Generic.IList`1[[Shiny.BluetoothLE.ScanResult, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ForwardOnNext(IList`1 value)
   at System.Reactive.Linq.ObservableImpl.Buffer`1.TimeHopping._[[Shiny.BluetoothLE.ScanResult, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]].Tick()
   at System.Reactive.Linq.ObservableImpl.Buffer`1.TimeHopping._.<>c[[Shiny.BluetoothLE.ScanResult, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]].<Run>b__4_0(_ this)
   at System.Reactive.Concurrency.Scheduler.<>c__67`1[[System.Reactive.Linq.ObservableImpl.Buffer`1.TimeHopping._[[Shiny.BluetoothLE.ScanResult, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].<SchedulePeriodic>b__67_0(ValueTuple`2 t)
   at System.Reactive.Concurrency.DefaultScheduler.PeriodicallyScheduledWorkItem`1.<>c[[System.ValueTuple`2[[System.Reactive.Linq.ObservableImpl.Buffer`1.TimeHopping._[[Shiny.BluetoothLE.ScanResult, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263],[System.Action`1[[System.Reactive.Linq.ObservableImpl.Buffer`1.TimeHopping._[[Shiny.BluetoothLE.ScanResult, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<Tick>b__5_0(PeriodicallyScheduledWorkItem`1 closureWorkItem)
   at System.Reactive.Concurrency.AsyncLock.<>c__5`1[[System.Reactive.Concurrency.DefaultScheduler.PeriodicallyScheduledWorkItem`1[[System.ValueTuple`2[[System.Reactive.Linq.ObservableImpl.Buffer`1.TimeHopping._[[Shiny.BluetoothLE.ScanResult, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263],[System.Action`1[[System.Reactive.Linq.ObservableImpl.Buffer`1.TimeHopping._[[Shiny.BluetoothLE.ScanResult, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].<Wait>b__5_0(Delegate actionObject, Object stateObject)
   at System.Reactive.Concurrency.AsyncLock.Wait(Object state, Delegate delegate, Action`2 action)
   at System.Reactive.Concurrency.AsyncLock.Wait[PeriodicallyScheduledWorkItem`1](PeriodicallyScheduledWorkItem`1 state, Action`1 action)
   at System.Reactive.Concurrency.DefaultScheduler.PeriodicallyScheduledWorkItem`1[[System.ValueTuple`2[[System.Reactive.Linq.ObservableImpl.Buffer`1.TimeHopping._[[Shiny.BluetoothLE.ScanResult, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263],[System.Action`1[[System.Reactive.Linq.ObservableImpl.Buffer`1.TimeHopping._[[Shiny.BluetoothLE.ScanResult, Shiny.BluetoothLE, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Tick()
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.PeriodicTimer.Tick()
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.PeriodicTimer.<>c.<.ctor>b__2_0(Object this)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__27_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.DispatchItemWithAutoreleasePool(Object workItem, Thread currentThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
Please submit PR's for your own corner cases in the future.  You can try/catch this yourself.
