### ISSUE TITLE
[Android] Apps may not schedule more than 100 distinct jobs

### ISSUE THREAD

**Issue by dahlbyk** [shinyorg/shiny#192]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] Android

## Feature Library

 - [x] Core (Jobs)
 - [ ] Locations
 - [ ] Notifications

## Version of Library

888293e9c86862a26eff15fed397cd864230b52a

## Version of OS(s) listed above with issue

Android 9

## Steps to Reproduce

Here's our `ShinyStartup`; delegate/job details don't seem relevant. We don't `RegisterJob()` anywhere else in the app, though previous iterations did. Is it possible there's some sort of lingering obsolete jobs?

```csharp
        public override void ConfigureServices(IServiceCollection builder)
        {
            // custom logging
            Log.UseConsole();
            Log.UseDebug();
            Log.AddLogger(new AppCenterLogger());

            // register all of the acr stuff you want to use
            builder.UseGeofencing<ShinyGeoFenceService.GeofenceProcessor>();
            builder.UseGps();
            builder.AddSingleton<IGeoFenceService, ShinyGeoFenceService>();

            builder.UseNotifications(true);
            builder.AddSingleton<INotificationDelegate, NullNotificationDelegate>();

            builder.RegisterJob(new JobInfo(typeof(ShinyGeoFenceService.GeofenceProcessor))
            {
                IsSystemJob = true,
                RequiredInternetAccess = InternetAccess.Any
            });
        }
```

## Expected Behavior

No crash; if `AbstractJobManager.Schedule()` does fail, maybe `catch`/`Log`?

## Actual Behavior

Crash loop with `java.lang.IllegalStateException`: **Apps may not schedule more than 100 distinct jobs**

```
Version Code: 1578438931
Version Name: 0.1.0+5ab31d9
Android: 9
Android Build: PPR1.180610.011
Manufacturer: samsung
Model: SM-G950U1
CrashReporter Key: 884c72e1-0197-4608-88a6-b964de9f6bc3
Start Date: 2020-01-09T00:00:35.373Z
Date: 2020-01-09T00:00:36.452Z

Xamarin Exception Stack:
Java.Lang.RuntimeException: Apps may not schedule more than 100 distinct jobs
  at Java.Interop.JniEnvironment+InstanceMethods.CallIntMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <70ee29fa8fd941eeaf9f13e6aaf052f3>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractInt32Method (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00014] in <70ee29fa8fd941eeaf9f13e6aaf052f3>:0
  at Android.App.Job.JobSchedulerInvoker.Schedule (Android.App.Job.JobInfo job) [0x00031] in <afbb6c3f690b4bfd842a7ad82c12ff7c>:0
  at Shiny.Jobs.JobManager.ScheduleNative (Shiny.Jobs.JobInfo jobInfo) [0x00102] in <a906b14214384c2a80e095294a0148c6>:0
  at Shiny.Jobs.AbstractJobManager.Schedule (Shiny.Jobs.JobInfo jobInfo) [0x00029] in <a906b14214384c2a80e095294a0148c6>:0
  at Shiny.ServiceExtensions+<>c__DisplayClass3_0.<RegisterJob>b__0 (System.IServiceProvider sp) [0x000e8] in <a906b14214384c2a80e095294a0148c6>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <a05bd567471f4f40ba64b0e0a2924c06>:0
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <afbb6c3f690b4bfd842a7ad82c12ff7c>:0
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <afbb6c3f690b4bfd842a7ad82c12ff7c>:0
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <afbb6c3f690b4bfd842a7ad82c12ff7c>:0
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.19(intptr,intptr)
  at java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
  at android.os.Parcel.createException(Parcel.java:1974)
  at android.os.Parcel.readException(Parcel.java:1934)
  at android.os.Parcel.readException(Parcel.java:1884)
  at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:184)
  at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
  at md5fcfe03c74613c9c105f854ab331bd247.MainApplication.n_onCreate(Native Method)
  at md5fcfe03c74613c9c105f854ab331bd247.MainApplication.onCreate(MainApplication.java:25)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6245)
  at android.app.ActivityThread.access$1200(ActivityThread.java:238)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1787)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:214)
  at android.app.ActivityThread.main(ActivityThread.java:7073)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
  at Caused by: android.os.RemoteException: Remote stack trace:
  at com.android.server.job.JobSchedulerService.scheduleAsPackage(JobSchedulerService.java:879)
  at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2621)
  at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:60)
  at android.os.Binder.execTransact(Binder.java:739)
--- End of inner exception stack trace ---
  Java.Lang.Exception: Remote stack trace:
	at com.android.server.job.JobSchedulerService.scheduleAsPackage(JobSchedulerService.java:879)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2621)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:60)
	at android.os.Binder.execTransact(Binder.java:739)

    at android.os.RemoteException: Remote stack trace:
    at com.android.server.job.JobSchedulerService.scheduleAsPackage(JobSchedulerService.java:879)
    at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2621)
    at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:60)
    at android.os.Binder.execTransact(Binder.java:739)

Thread 2:
0   dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
1   java.lang.Thread.getStackTrace(Thread.java:1538)
2   java.lang.Thread.getAllStackTraces(Thread.java:1588)
3   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:1093)
4   com.microsoft.appcenter.crashes.WrapperSdkExceptionManager.saveWrapperException(WrapperSdkExceptionManager.java:58)
5   mono.java.lang.RunnableImplementor.n_run(RunnableImplementor.java:-2)
6   mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
7   android.os.Handler.handleCallback(Handler.java:873)
8   android.os.Handler.dispatchMessage(Handler.java:99)
9   android.os.Looper.loop(Looper.java:214)
10  android.app.ActivityThread.main(ActivityThread.java:7073)
11  java.lang.reflect.Method.invoke(Method.java:-2)
12  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
13  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

Thread 2282:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:178)
2   java.lang.Daemons$Daemon.run(Daemons.java:103)
3   java.lang.Thread.run(Thread.java:764)

Thread 2283:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:422)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
4   java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:232)
5   java.lang.Daemons$Daemon.run(Daemons.java:103)
6   java.lang.Thread.run(Thread.java:764)

Thread 2284:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:297)
2   java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:277)
3   java.lang.Daemons$Daemon.run(Daemons.java:103)
4   java.lang.Thread.run(Thread.java:764)

Thread 2294:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:326)
2   android.os.Looper.loop(Looper.java:181)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 2296:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:326)
2   android.os.Looper.loop(Looper.java:181)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 2297:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:326)
2   android.os.Looper.loop(Looper.java:181)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 2298:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:326)
2   android.os.Looper.loop(Looper.java:181)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 2306:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2137)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.poll(ScheduledThreadPoolExecutor.java:1168)
6   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.poll(ScheduledThreadPoolExecutor.java:849)
7   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091)
8   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
9   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10  com.google.android.gms.common.util.concurrent.zza.run
11  java.lang.Thread.run(Thread.java:764)
```

**Comment by aritchie** [comment]
It is supposed to be cancelling the job before updating it.  I put a potential fix into dev just now for this

**Comment by dahlbyk** [comment]
> I put a potential fix into dev just now for this

e1ee90626fb9065c15c010a642e2d3f3b5199a3e, for anyone looking.
