### ISSUE TITLE
Shiny.Locations - Method non existent on android 7.0

### ISSUE THREAD

**Issue by Syntherz** [shinyorg/shiny#329]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS

## Feature Library (beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!)

 - [ ] Core
 - [X] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] Push (beta)
 - [ ] SQLite Integration (beta)

## Version of Library

1.1.0.1570

## Version of OS(s) listed above with issue

Android 7.0 Nougat

## Steps to Reproduce

1. In a Xamarin.Forms project, install the plugin Shiny.Locations on the android project and create the needed classes/code as shown in the tutorials;
2. In a class, create 2 objects with the following types: IGpsListener and IGpsManager;
3. In the same class, associate the event OnReadingReceived existent on the object with the type IGpsListener to a desired Method;
4. Still on the same class, start the listener with the method StartListener() existent on the object with the type IGpsManager;
5. Run the project to the point where it tries to execute the steps described above.

Here goes the code in C# that i use to do step 2, 3 and 4:

//Variables
IGpsListener _gpsListener;
IGpsManager _gpsManager;

//Methods
protected async void StartGpsListener()
        {
            try
            {

                if(_gpsListener != null)
                {
                    //Associate the event OnReadingReceived to a desired Method
                    _gpsListener.OnReadingReceived += Method_OnGPSReadingReceived;

                    //Start the listener
                    await _gpsManager.StartListener(new GpsRequest
                    {
                        UseBackground = true,
                        Priority = GpsPriority.Highest,
                        Interval = TimeSpan.FromSeconds(8),
                        ThrottledInterval = TimeSpan.FromSeconds(3)
                    });
                }
            }
            catch (Exception ex)
            {
                App.ErrorLog(ex);
            }
        }

## Expected Behavior

Start the listener, and run the Method_OnGPSReadingReceived() each time the event OnReadingReceived occurs. 

It's important to notice that this implementation works if the android has the version 9 or above.

## Actual Behavior

It fails to execute the StartListener method, generating the following error:

Java.Lang.NoSuchMethodError: no non-static method "Landroid/location/LocationManager;.isLocationEnabled()Z"
  at Java.Interop.JniEnvironment+InstanceMethods.GetMethodID (Java.Interop.JniObjectReference type, System.String name, System.String signature) [0x0005b] in <26521a5118b44c858c385715922b9d5d>:0 
  at Java.Interop.JniType.GetInstanceMethod (System.String name, System.String signature) [0x0000c] in <26521a5118b44c858c385715922b9d5d>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.GetMethodInfo (System.String encodedMember) [0x00031] in <26521a5118b44c858c385715922b9d5d>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualBooleanMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001c] in <26521a5118b44c858c385715922b9d5d>:0 
  at Android.Locations.LocationManager.get_IsLocationEnabled () [0x0000a] in <d3b924763d4a465c85b26f6e8edc8a53>:0 
  at Shiny.Locations.PlatformExtensions.GetLocationManagerStatus (Shiny.AndroidContext context, System.Boolean gpsRequired) [0x0000c] in d:\a\1\s\src\Shiny.Locations\Platforms\Android\PlatformExtensions.cs:20 
  at Shiny.Locations.PlatformExtensions.RequestLocationAccess (Shiny.AndroidContext context, System.Boolean background, System.Boolean fineAccess) [0x00014] in d:\a\1\s\src\Shiny.Locations\Platforms\Android\PlatformExtensions.cs:51 
  at Shiny.Locations.GpsManagerImpl.StartListener (Shiny.Locations.GpsRequest request) [0x0004c] in d:\a\1\s\src\Shiny.Locations\Platforms\Android\GpsManagerImpl.cs:56 
  at Enterprise.MyApp.App.ViewModels.Shared.SharedViewModel.StartGpsListener () [0x00148] in C:\Projetos\BDProjeto\Enterprise.MyApp.App.Moto\Enterprise.MyApp.App.Moto\ViewModels\Shared\SharedViewModel.cs:2000 
  --- End of managed Java.Lang.NoSuchMethodError stack trace ---
java.lang.NoSuchMethodError: no non-static method "Landroid/location/LocationManager;.isLocationEnabled()Z"
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

I'm assuming it's because the android version 7.0 doesn't recognize the method isLocationEnabled() existent on the class PlatformExtensions of your Shiny.Locations plugin. Because, as i said before, it works fine on the version 9 and above. Wich leads me to wonder if it's a bug, or if it's just Shiny.Locations that doesn't support this android version.

It's my first time writing a bug report, so be kind, if more information is needed just tell me! Thanks in advance for your help.

**Comment by aritchie** [comment]
Please try the dev version on myget as this has already been fixed

**Comment by Syntherz** [comment]
Thank you very much! The error was fixed when i installed the newer versions on myget. But with that a question arised.

I don't know if i should create a new issue or not here, but following the code i posted here, the part where i associate the event with the method ( _gpsListener.OnReadingReceived += Method_OnGPSReadingReceived;) isn't working anymore with the newer versions of the Shiny.Locations, the method is never called.

Perhaps the way to do this with prism on a xamarin.forms project changed with the newer versions?

**Comment by aritchie** [comment]
@Syntherz Support is only available to project sponsors under a different category.  This bug is already completed.
