### ISSUE TITLE
[Preview Branch] Core UWP - Exception on startup: Newtonsoft.Json.JsonSerializationException

### ISSUE THREAD

**Issue by DigitalNut** [shinyorg/shiny#447]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [X] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [X] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
Preview branch - Pulled Nov 5, 2020
## Version of OS(s) listed above with issue
Windows 10 UWP platform (Windows version 2004 - OS Build 19041.572)

## Steps to Reproduce
1. Create Xamarin Uwp project with Shiny Bluetooth
2. Call this.ShinyInit(new ShinyAppStartup()); in App.xmal.cs in UWP project
3. Exception thrown in Shiny.Core.dll!Shiny.Infrastructure.ShinySerializer.Serialize(object value) Line 12
	at C:\DevTemp\Git\shiny\src\Shiny.Core\Infrastructure\ShinySerializer.cs(12)

## Expected Behavior
No crash

## Actual Behavior
Exception thrown

**Stack Trace:**
```
Newtonsoft.Json.JsonSerializationException
  HResult=0x80131500
  Message=Self referencing loop detected for property 'ManifestModule' with type 'System.Reflection.RuntimeModule'. Path '[7].ImplementationFactory.Method.Module.Assembly'.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
   at Shiny.Infrastructure.ShinySerializer.Serialize(Object value) in C:\DevTemp\Git\shiny\src\Shiny.Core\Infrastructure\ShinySerializer.cs:line 12
   at Shiny.UwpPlatform.<>c.<Register>b__5_0(IServiceProvider sp) in C:\DevTemp\Git\shiny\src\Shiny.Core\Platforms\Uwp\UwpPlatform.cs:line 36
   at Shiny.Extensions_ServiceCollection.BuildShinyServiceProvider(IServiceCollection services, Boolean validateScopes, Func`2 containerBuild, Action`1 assignBeforeEvents) in C:\DevTemp\Git\shiny\src\Shiny.Core.Abstractions\Extensions_ServiceCollection.cs:line 70
   at Shiny.ShinyHost.Init(IPlatform platform, IShinyStartup startup, Action`1 platformBuild) in C:\DevTemp\Git\shiny\src\Shiny.Core.Abstractions\ShinyHost.cs:line 100
   at Shiny.PlatformExtensions.ShinyInit(Application app, IShinyStartup startup) in C:\DevTemp\Git\shiny\src\Shiny.Core\Platforms\Uwp\PlatformExtensions.cs:line 11
   at FieldUtilityApp.UWP.App..ctor() in C:\DevTemp\FieldUtilityAppShiny\FieldUtilityApp.UWP\App.xaml.cs:line 35
   at FieldUtilityApp.UWP.Program.<>c.<Main>b__0_0(ApplicationInitializationCallbackParams p) in C:\DevTemp\FieldUtilityAppShiny\FieldUtilityApp.UWP\obj\x86\Debug\App.g.i.cs:line 24

  This exception was originally thrown at this call stack:
    [External Code]
    Shiny.Infrastructure.ShinySerializer.Serialize(object) in ShinySerializer.cs
    Shiny.UwpPlatform.Register.AnonymousMethod__5_0(System.IServiceProvider) in UwpPlatform.cs
    Shiny.Extensions_ServiceCollection.BuildShinyServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection, bool, System.Func<Microsoft.Extensions.DependencyInjection.IServiceCollection, System.IServiceProvider>, System.Action<System.IServiceProvider>) in Extensions_ServiceCollection.cs
    Shiny.ShinyHost.Init(Shiny.IPlatform, Shiny.IShinyStartup, System.Action<Microsoft.Extensions.DependencyInjection.IServiceCollection>) in ShinyHost.cs
    Shiny.PlatformExtensions.ShinyInit(Windows.UI.Xaml.Application, Shiny.IShinyStartup) in PlatformExtensions.cs
    FieldUtilityApp.UWP.App.App() in App.xaml.cs
    FieldUtilityApp.UWP.Program.Main.AnonymousMethod__0_0(Windows.UI.Xaml.ApplicationInitializationCallbackParams) in App.g.i.cs
```

**Comment by aritchie** [comment]
UWP is not done on preview yet so this is known
