### ISSUE TITLE
[Bug] ProGuard issue while loading JobManager

### ISSUE THREAD

**Issue by diegostamigni** [shinyorg/shiny#62]
- [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [x] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.306-beta

## Version of OS(s) listed above with issue
Android Nougat
macOS 10.14.5

## Steps to Reproduce
1. Use the JobManager
2. Enable proguard
3. Run a release build

## Expected Behavior
The app should run

## Actual Behavior
The app crashes with the following stacktrace:

```
[AndroidRuntime] android.runtime.JavaProxyThrowable: System.InvalidOperationException: A suitable constructor for type 'Shiny.Jobs.JobManager' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
[AndroidRuntime]   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite (System.Type serviceType, System.Type implementationType, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain callSiteChain) <0x70949479bc + 0x00604> in <fb52042823624ebebed2e179ffd81a72>:0 
[AndroidRuntime]   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact (Microsoft.Extensions.DependencyInjection.ServiceDescriptor descriptor, System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain callSiteChain) <0x7094947654 + 0x000f7> in <fb52042823624ebebed2e179ffd81a72>:0 
[AndroidRuntime]   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact (System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain callSiteChain) <0x7094947198 + 0x0006b> in <fb52042823624ebebed2e179ffd81a72>:0 
[AndroidRuntime]   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite (System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain callSiteChain) <0x709494e910 + 0x000d3> in <fb52042823624ebebed2e179ffd81a72>:0 
[AndroidRuntime]   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor (System.Type serviceType) <0x709494bae0 + 0x00057> in <fb52042823624ebebed2e179ffd81a72>:0 
[AndroidRuntime]   at System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue].GetOrAdd (TKey key, System.Func`2[T,TResult] valueFactory) <0x709667cf98 + 0x000b7> in <3361a83b4b6d4cc080edaa4305dde75a>:0 
[AndroidRuntime]   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService (System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope serviceProviderEngineScope) <0x709494ba48 + 0x0004f> in <fb52042823624ebebed2e179ffd81a72>:0 
[AndroidRuntime]   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService (System.Type serviceType) <0x709494b9c8 + 0x00037> in <fb52042823624ebebed2e179ffd81a72>:0 
[AndroidRuntime]   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService (System.Type serviceType) <0x70949465f4 + 0x0003f> in <fb52042823624ebebed2e179ffd81a72>:0 
[AndroidRuntime]   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T] (System.IServiceProvider provider) <0x7094987c38 + 0x0004b> in <030cd78051ca465b832cd0396110c776>:0 
[AndroidRuntime]   at Shiny.ShinyHost.Resolve[T] () <0x70940e3374 + 0x00043> in <7edbfa27e30b4fa49e15e63d72961701>:0 
[AndroidRuntime]   at MyTV.Core.IoCRegistry.RegisterUtils (Autofac.ContainerBuilder builder) <0x709468a534 + 0x0028b> in <50a8c70db1cd4b7e829bf4b707904c10>:0 
[AndroidRuntime]   at MyTV.Core.IoCRegistry.RegisterCore (Autofac.ContainerBuilder builder, System.Collections.Generic.IEnumerable`1[T] additionalProfiles) <0x7094689d00 + 0x0006f> in <50a8c70db1cd4b7e829bf4b707904c10>:0 
[AndroidRuntime]   at MyTV.Droid.Setup.CreateIocProvider () <0x7092fb5ae0 + 0x00057> in <3bb21387111146fbbbc508cd947328f1>:0 
[AndroidRuntime]   at MvvmCross.Core.MvxSetup.InitializeIoC () <0x709566fc2c + 0x00033> in <4562264c3faf4096ab0448a5898edfdf>:0 
[AndroidRuntime]   at MvvmCross.Core.MvxSetup.InitializePrimary () <0x709566f3cc + 0x00047> in <4562264c3faf4096ab0448a5898edfdf>:0 
[AndroidRuntime]   at MvvmCross.Core.MvxSetupSingleton.StartSetupInitialization () <0x7095672014 + 0x00053> in <4562264c3faf4096ab0448a5898edfdf>:0 
[AndroidRuntime]   at MvvmCross.Core.MvxSetupSingleton.EnsureInitialized () <0x7095671c10 + 0x000cb> in <4562264c3faf4096ab0448a5898edfdf>:0 
[AndroidRuntime]   at MvvmCross.Platforms.Android.Views.MvxActivityViewExtensions.EnsureSetupInitialized (MvvmCross.Platforms.Android.Views.IMvxAndroidView androidView) <0x709563fb70 + 0x0008f> in <4562264c3faf4096ab0448a5898edfdf>:0 
[AndroidRuntime]   at MvvmCross.Platforms.Android.Views.MvxActivityViewExtensions.OnViewCreate (MvvmCross.Platforms.Android.Views.IMvxAndroidView androidView, Android.OS.Bundle bundle) <0x709563f1cc + 0x00073> in <4562264c3faf4096ab0448a5898edfdf>:0 
[AndroidRuntime]   at MvvmCross.Platforms.Android.Views.MvxActivityAdapter.EventSourceOnCreateCalled (System.Object sender, MvvmCross.Base.MvxValueEventArgs`1[T] eventArgs) <0x709563ec28 + 0x000a3> in <4562264c3faf4096ab0448a5898edfdf>:0 
[AndroidRuntime]   at (wrapper delegate-invoke) System.EventHandler`1[MvvmCross.Base.MvxValueEventArgs`1[Android.OS.Bundle]].invoke_void_object_TEventArgs(object,MvvmCross.Base.MvxValueEventArgs`1<Android.OS.Bundle>)
[AndroidRuntime]   at MvvmCross.Base.MvxDelegateExtensions.Raise[T] (System.EventHandler`1[TEventArgs] eventHandler, System.Object sender, T value) <0x709569379c + 0x00067> in <4562264c3faf4096ab0448a5898edfdf>:0 
[AndroidRuntime]   at MvvmCross.Droid.Support.V7.AppCompat.EventSource.MvxEventSourceAppCompatActivity.OnCreate (Android.OS.Bundle bundle) <0x70947d35a4 + 0x0005f> in <9874589629f845c7b92ca47830098dae>:0 
[AndroidRuntime]   at MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatActivity.OnCreate (Android.OS.Bundle bundle) <0x70947c4590 + 0x00033> in <9874589629f845c7b92ca47830098dae>:0 
[AndroidRuntime]   at MyTV.Droid.Views.BaseActivity`1[TViewModel].OnCreate (Android.OS.Bundle bundle) <0x7092fb5bdc + 0x00037> in <3bb21387111146fbbbc508cd947328f1>:0 
[AndroidRuntime]   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) <0x70960ed740 + 0x0006f> in <b297454edca84df9b51feeff14951c94>:0 
[AndroidRuntime]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.19(intptr,intptr,intptr)
[AndroidRuntime] 	at md51956971b8a87a8f55af6e317984e9bb2.BaseActivity_1.n_onCreate(Native Method)
[AndroidRuntime] 	at md51956971b8a87a8f55af6e317984e9bb2.BaseActivity_1.onCreate(BaseActivity_1.java:30)
[AndroidRuntime] 	at android.app.Activity.performCreate(Activity.java:7144)
[AndroidRuntime] 	at android.app.Activity.performCreate(Activity.java:7135)
[AndroidRuntime] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
[AndroidRuntime] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
[AndroidRuntime] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
[AndroidRuntime] 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
[AndroidRuntime] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
[AndroidRuntime] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:193)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:6718)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[Process] Sending signal. PID: 27091 SIG: 9
```

**Comment by aritchie** [comment]
This is more likely a linker issue than a proguard one.  Since classes and things are still likely to shift, I’m not touching or documenting this until the end
