### ISSUE TITLE
[Bug]: Xamarin Android 12 : Shiny Location API : Geofence : Exception thrown while Start Monitoring region : Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent

### ISSUE THREAD

**Issue by hardikphd** [shinyorg/shiny#891]
### Component/Nuget

GPS, Geofencing, Motion Activity (Shiny.Locations)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [X] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

1. Download attached Project
2. Run on Android 12 Device or Android Emulator
3. Click on "Check Geofencing" Button on About Page
4. Choose "Allow all the  time" when asked for Location Permission
5. Exception occurs while StartMonitoring method

### Expected Behavior

No Exception

### Actual Behavior

Geo fencing does not work on Android 12 device.

### Exception or Log output

{Java.Lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <dd8770963db64939be322a2c6d46563b>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <dd8770963db64939be322a2c6d46563b>:0 
  at Android.App.PendingIntent.GetBroadcast (Android.Content.Context context, System.Int32 requestCode, Android.Content.Intent intent, Android.App.PendingIntentFlags flags) [0x00075] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-31/mcw/Android.App.PendingIntent.cs:624 
  at Shiny.Locations.GeofenceManagerImpl.GetPendingIntent () [0x00035] in <df9de446eeb849dab592956fe3356513>:0 
  at Shiny.Locations.GeofenceManagerImpl.Create (Shiny.Locations.GeofenceRegion region) [0x0009b] in <df9de446eeb849dab592956fe3356513>:0 
  at Shiny.Locations.GeofenceManagerImpl.StartMonitoring (Shiny.Locations.GeofenceRegion region) [0x000f2] in <df9de446eeb849dab592956fe3356513>:0 
  at Tego.App.Interface.LocationHelper+<>c__DisplayClass14_1.<GetCurrentGeoLocationAsync>b__0 (TegoCloud.Models.DeviceLocation location) [0x00136] in C:\Users\HardikPatel\source\tego-apps\Tego.AppInterface\Tego.App.Interface\{Location}\LocationHelper.cs:157 
  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: tego.mrohistorian: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
	at crc64a0e0a82d0db9a07d.SingleLocationListener.n_onLocationChanged(Native Method)
	at crc64a0e0a82d0db9a07d.SingleLocationListener.onLocationChanged(SingleLocationListener.java:34)
	at android.location.LocationListener.onLocationChanged(LocationListener.java:63)
	at android.location.LocationManager$LocationListenerTransport$1.operate(LocationManager.java:3180)
	at android.location.LocationManager$LocationListenerTransport$1.operate(LocationManager.java:3177)
	at com.android.internal.listeners.ListenerExecutor.lambda$executeSafely$0(ListenerExecutor.java:127)
	at com.android.internal.listeners.ListenerExecutor$$ExternalSyntheticLambda0.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
}

### Code Sample

[ShinyGeoFenceTest.zip](https://github.com/shinyorg/shiny/files/7930329/ShinyGeoFenceTest.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
You are best to set your major target to 11 since that is what Shiny currently tests and is compiled against.  This is a bug but not one there will be others so I'm not actively engaging in all of them yet since XF itself only targets android 11 as well.

**Comment by hardikphd** [comment]
Working as expected with Android 11, only when "Allow all the time" permission is given.

**Comment by hardikphd** [comment]
@aritchie Thanks for your reply.

**Comment by Dipannita20** [comment]
@aritchie  Is this expected to be resolved in **2.5.0-preview.3045(Major target is now Android 12).** Getting below error with 2.5.0-preview.3045

`[0:] Java.Lang.IllegalArgumentException:  Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <2e109281f9514c53b44688fd4549adb2>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <2e109281f9514c53b44688fd4549adb2>:0 
  at Android.App.PendingIntent.GetBroadcast (Android.Content.Context context, System.Int32 requestCode, Android.Content.Intent intent, Android.App.PendingIntentFlags flags) [0x00075] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-31/mcw/Android.App.PendingIntent.cs:524 
  at Shiny.Locations.GeofenceManagerImpl.GetPendingIntent () [0x00035] in <557589efa1ff40519c37af34ac92656f>:0 
  at Shiny.Locations.GeofenceManagerImpl.Create (Shiny.Locations.GeofenceRegion region) [0x0009b] in <557589efa1ff40519c37af34ac92656f>:0 
  at Shiny.Locations.GeofenceManagerImpl.StartMonitoring (Shiny.Locations.GeofenceRegion region) [0x000f2] in <557589efa1ff40519c37af34ac92656f>:0 
  
  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: com.dciartform.brandambassador.soa.dev: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)`
