### ISSUE TITLE
[Bug]: Android 12 not working

### ISSUE THREAD

**Issue by bluekuen** [shinyorg/shiny#915]
### Component/Nuget

Shiny.Core (Settings, Startup)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [X] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

1. create new xamarin forms project
2. install shiny
3. follow setup guide
4. target android 12
5. build and run

### Expected Behavior

Building and running

### Actual Behavior

Exception:

Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.'

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Please include the entire stack trace.  I don’t think these issues are coming for the core at all.  

As a suggestion, there is currently no value in major targeting Android 12.  Xamarin forms doesn’t, shiny doesn’t, and none of the 3rd party ecosystem does it (that I’ve seen)

**Comment by Colipe1** [comment]
Sure, the entire build output is below. I didn't actually select Android 12. I think GitHub did that by default when I submitted the issue.

Rebuild started...
1>------ Rebuild All started: Project: Sample.Shared, Configuration: Debug Any CPU ------
Restored C:\Users\cshipe\Downloads\samples-main\Beacons\Sample.iOS\Sample.iOS.csproj (in 1.05 sec).
Restored C:\Users\cshipe\Downloads\samples-main\_Template\Sample.Shared\Sample.Shared.csproj (in 1.05 sec).
Restored C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\Sample.csproj (in 1.05 sec).
Restored C:\Users\cshipe\Downloads\samples-main\Beacons\Sample.Android\Sample.Android.csproj (in 1.09 sec).
1>C:\Users\cshipe\Downloads\samples-main\_Template\Sample.Shared\Infrastructure\ShinyEvent.cs(12,23,12,27): warning CS8618: Non-nullable property 'Text' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
1>C:\Users\cshipe\Downloads\samples-main\_Template\Sample.Shared\Infrastructure\ShinyEvent.cs(13,23,13,29): warning CS8618: Non-nullable property 'Detail' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
1>C:\Users\cshipe\Downloads\samples-main\_Template\Sample.Shared\Infrastructure\SampleViewModel.cs(19,13,19,35): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
1>C:\Users\cshipe\Downloads\samples-main\_Template\Sample.Shared\LogsViewModel.cs(11,16,11,29): warning CS8618: Non-nullable field 'events' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.
1>Sample.Shared -> C:\Users\cshipe\Downloads\samples-main\_Template\Sample.Shared\bin\Debug\netstandard2.0\Sample.Shared.dll
1>Done building project "Sample.Shared.csproj".
2>------ Rebuild All started: Project: Sample, Configuration: Debug Any CPU ------
2>CSC : warning CS8032: An instance of analyzer Shiny.Generators.AndroidActivitySourceGenerator cannot be created from C:\Users\cshipe\.nuget\packages\shiny\2.5.0.2985-preview\analyzers\dotnet\cs\Shiny.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
2>CSC : warning CS8032: An instance of analyzer Shiny.Generators.AndroidApplicationSourceGenerator cannot be created from C:\Users\cshipe\.nuget\packages\shiny\2.5.0.2985-preview\analyzers\dotnet\cs\Shiny.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
2>CSC : warning CS8032: An instance of analyzer Shiny.Generators.iOSAppDelegateSourceGenerator cannot be created from C:\Users\cshipe\.nuget\packages\shiny\2.5.0.2985-preview\analyzers\dotnet\cs\Shiny.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
2>CSC : warning CS8032: An instance of analyzer Shiny.Generators.StaticClassSourceGenerator cannot be created from C:\Users\cshipe\.nuget\packages\shiny\2.5.0.2985-preview\analyzers\dotnet\cs\Shiny.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
2>CSC : warning CS8032: An instance of analyzer Shiny.Generators.UwpSourceGenerator cannot be created from C:\Users\cshipe\.nuget\packages\shiny\2.5.0.2985-preview\analyzers\dotnet\cs\Shiny.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\MainPage.xaml.cs(5,37,5,53): warning CS0618: 'MasterDetailPage' is obsolete: 'MasterDetailPage is obsolete as of version 5.0.0. Please use FlyoutPage instead.'
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\obj\Debug\netstandard2.0\MainPage.xaml.g.cs(17,37,17,75): warning CS0618: 'MasterDetailPage' is obsolete: 'MasterDetailPage is obsolete as of version 5.0.0. Please use FlyoutPage instead.'
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\MonitoringViewModel.cs(40,29,40,38): warning CS8602: Dereference of a possibly null reference.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\MonitoringViewModel.cs(52,31,52,44): warning CS8602: Dereference of a possibly null reference.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\MonitoringViewModel.cs(18,16,18,35): warning CS8618: Non-nullable property 'Regions' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\RangingViewModel.cs(44,48,44,59): warning CS8604: Possible null reference argument for parameter 'value' in 'INavigationParameters Extensions.Set(INavigationParameters parameters, string key, object value)'.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\RangingViewModel.cs(22,16,22,32): warning CS8618: Non-nullable property 'Uuid' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\RangingViewModel.cs(22,16,22,32): warning CS8618: Non-nullable property 'Major' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\RangingViewModel.cs(22,16,22,32): warning CS8618: Non-nullable property 'Minor' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\RangingViewModel.cs(61,34,61,38): warning CS8625: Cannot convert null literal to non-nullable reference type.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\RangingViewModel.cs(65,30,65,61): warning CS8601: Possible null reference assignment.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\RangingViewModel.cs(66,30,66,61): warning CS8601: Possible null reference assignment.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\CreateViewModel.cs(23,38,23,59): warning CS8601: Possible null reference assignment.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\CreateViewModel.cs(24,40,24,63): warning CS8601: Possible null reference assignment.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\CreateViewModel.cs(40,40,40,54): warning CS8602: Dereference of a possibly null reference.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\CreateViewModel.cs(98,33,98,47): warning CS8602: Dereference of a possibly null reference.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\CreateViewModel.cs(103,33,103,47): warning CS8602: Dereference of a possibly null reference.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\CreateViewModel.cs(18,16,18,31): warning CS8618: Non-nullable property 'Identifier' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\CreateViewModel.cs(18,16,18,31): warning CS8618: Non-nullable property 'Uuid' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\CreateViewModel.cs(18,16,18,31): warning CS8618: Non-nullable property 'Major' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\CreateViewModel.cs(18,16,18,31): warning CS8618: Non-nullable property 'Minor' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\CreateViewModel.cs(18,16,18,31): warning CS8618: Non-nullable property 'NotificationTitle' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\CreateViewModel.cs(18,16,18,31): warning CS8618: Non-nullable property 'NotificationMessage' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
2>C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\RangingViewModel.cs(99,35,99,46): warning CS8604: Possible null reference argument for parameter 'region' in 'IObservable<Beacon> IBeaconRangingManager.WhenBeaconRanged(BeaconRegion region)'.
2>Sample -> C:\Users\cshipe\Downloads\samples-main\Beacons\Sample\bin\Debug\netstandard2.0\Sample.dll
2>Done building project "Sample.csproj".
3>------ Rebuild All started: Project: Sample.Android, Configuration: Debug Any CPU ------
3>CSC : warning CS8032: An instance of analyzer Shiny.Generators.AndroidActivitySourceGenerator cannot be created from C:\Users\cshipe\.nuget\packages\shiny\2.5.0.2985-preview\analyzers\dotnet\cs\Shiny.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
3>CSC : warning CS8032: An instance of analyzer Shiny.Generators.AndroidApplicationSourceGenerator cannot be created from C:\Users\cshipe\.nuget\packages\shiny\2.5.0.2985-preview\analyzers\dotnet\cs\Shiny.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
3>CSC : warning CS8032: An instance of analyzer Shiny.Generators.iOSAppDelegateSourceGenerator cannot be created from C:\Users\cshipe\.nuget\packages\shiny\2.5.0.2985-preview\analyzers\dotnet\cs\Shiny.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
3>CSC : warning CS8032: An instance of analyzer Shiny.Generators.StaticClassSourceGenerator cannot be created from C:\Users\cshipe\.nuget\packages\shiny\2.5.0.2985-preview\analyzers\dotnet\cs\Shiny.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
3>CSC : warning CS8032: An instance of analyzer Shiny.Generators.UwpSourceGenerator cannot be created from C:\Users\cshipe\.nuget\packages\shiny\2.5.0.2985-preview\analyzers\dotnet\cs\Shiny.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
3>  Sample.Android -> C:\Users\cshipe\Downloads\samples-main\Beacons\Sample.Android\bin\Debug\Sample.Android.dll
========== Rebuild All: 3 succeeded, 0 failed, 0 skipped ==========

**Comment by bluekuen** [comment]
Yes sure, forgot to attach it sorry:

```
[AndroidRuntime] java.lang.IllegalArgumentException: com.shiny.test: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
[AndroidRuntime] Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
[AndroidRuntime] 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
[AndroidRuntime] 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
[AndroidRuntime] 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
[AndroidRuntime] 	at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:273)
[AndroidRuntime] 	at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:151)
[AndroidRuntime] 	at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:171)
[AndroidRuntime] 	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:102)
[AndroidRuntime] 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
[AndroidRuntime] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[AndroidRuntime] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[AndroidRuntime] 	at java.lang.Thread.run(Thread.java:920)
Thread started:  #2
Loaded assembly: /data/data/com.shiny.test/files/.__override__/System.Core.dll [External]
**Java.Lang.IllegalArgumentException:** 'Loading...'

[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.IllegalArgumentException: com.shiny.test: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
[MonoDroid] Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
[MonoDroid]   --- End of managed Java.Lang.IllegalArgumentException stack trace ---
[MonoDroid] java.lang.IllegalArgumentException: com.shiny.test: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
[MonoDroid] Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
[MonoDroid] 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
[MonoDroid] 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
[MonoDroid] 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
[MonoDroid] 	at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:273)
[MonoDroid] 	at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:151)
[MonoDroid] 	at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:171)
[MonoDroid] 	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:102)
[MonoDroid] 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
[MonoDroid] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[MonoDroid] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[MonoDroid] 	at java.lang.Thread.run(Thread.java:920)
[MonoDroid] 
```

**Comment by aritchie** [comment]
This should be resolved on the latest preview version on nuget

**Comment by aritchie** [comment]
No reply from user - closing as per internal testing
